// FINTERM — industrias (subcategorías) por ticker. Baseline estático para que el
// filtro por industria del Dashboard esté completo desde el arranque; la industria
// real de Finnhub (profile2) tiene prioridad cuando se carga.
(function(){
  var M={};
  var G=function(ind,ts){ for(var i=0;i<ts.length;i++) M[ts[i]]=ind; };
  G('Semiconductores',["NVDA","AVGO","AMD","INTC","QCOM","TXN","AMAT","MU","LRCX","ADI","KLAC","MRVL","NXPI","MCHP","ON","TER","SWKS","QRVO","MPWR","FSLR","ENPH"]);
  G('Software',["MSFT","ORCL","CRM","ADBE","INTU","NOW","SNPS","CDNS","ADSK","ANSS","PTC","TYL","GEN","PLTR","WDAY","DDOG","MDB","APP","FICO","PAYC","DAY","VTEX"]);
  G('Ciberseguridad',["FTNT","CRWD","PANW"]);
  G('Servicios de TI',["ACN","IBM","IT","EPAM","CDW","GDDY","VRSN","JKHY"]);
  G('Computación',["AAPL","HPQ","HPE","DELL","WDC","STX","NTAP","SMCI"]);
  G('Redes y comunicaciones',["CSCO","ANET","JNPR","FFIV","AKAM","MSI"]);
  G('Electrónica',["APH","TEL","GLW","JBL","ZBRA","TDY","KEYS","TRMB","GRMN","MIRG"]);
  G('Internet y contenidos',["GOOGL","GOOG","META","MTCH","UBER"]);
  G('Comercio electrónico',["AMZN","EBAY","DASH","MELI"]);
  G('Medios',["NFLX","DIS","CMCSA","WBD","PARA","FOXA","FOX","NWSA","NWS","TKO","GCLA"]);
  G('Telecomunicaciones',["T","VZ","TMUS","CHTR","CVH","TECO2","TIMB","VIV"]);
  G('Videojuegos',["EA","TTWO"]);
  G('Publicidad',["OMC","IPG","TTD"]);
  G('Entretenimiento',["LYV"]);
  G('Automotrices',["TSLA","GM","F"]);
  G('Autopartes',["APTV","BWA","LKQ"]);
  G('Restaurantes',["MCD","SBUX","CMG","YUM","DRI","DPZ"]);
  G('Indumentaria y lujo',["NKE","LULU","DECK","RL","TPR"]);
  G('Comercio minorista',["HD","LOW","TSCO","TJX","ROST","BBY","ULTA","KMX","GPC","WSM","ORLY","AZO","WMT","COST","TGT","KR","DG","DLTR","WBA","POOL","HAS","PATA"]);
  G('Viajes',["BKNG","EXPE","ABNB"]);
  G('Hoteles y ocio',["MAR","HLT","CCL","RCL","NCLH","LVS","WYNN","MGM","CZR","BOLT"]);
  G('Construcción',["DHI","LEN","NVR","PHM","CARR","TT","OTIS","JCI","ALLE","MAS","AOS","BLDR","PWR","MHK"]);
  G('Productos del hogar',["PG","CL","KMB","CHD","CLX"]);
  G('Hogar (durables)',["LONG"]);
  G('Bebidas',["KO","PEP","MNST","KDP","STZ","TAP","BF.B","ABEV"]);
  G('Tabaco',["PM","MO"]);
  G('Alimentos',["MDLZ","GIS","KHC","HSY","K","CAG","CPB","TSN","HRL","SJM","MKC","ADM","BG","LW","SYY","AGRO","LEDE","MOLI","MOLA","MORI","SAMI","INVJ","BRFS","JBSAY","LND"]);
  G('Cuidado personal',["KVUE","EL"]);
  G('Farmacéuticas',["LLY","ABBV","MRK","PFE","BMY","JNJ","ZTS","VTRS","RICH"]);
  G('Biotecnología',["AMGN","GILD","VRTX","REGN","BIIB","MRNA","INCY"]);
  G('Dispositivos médicos',["ABT","MDT","ISRG","BSX","SYK","EW","ZBH","BDX","STE","BAX","HOLX","ALGN","PODD","DXCM","RMD","IDXX","GEHC","WST","SOLV"]);
  G('Ciencias de la vida',["TMO","DHR","A","MTD","WAT","RVTY","TECH","CRL","IQV"]);
  G('Servicios de salud',["UNH","CI","ELV","CVS","CNC","MOH","HCA","UHS","DVA","LH","DGX","AFYA"]);
  G('Bancos',["JPM","BAC","WFC","C","USB","PNC","TFC","MTB","FITB","HBAN","RF","CFG","KEY","GGAL","BMA","BBAR","SUPV","VALO","ITUB","BBD","BSBR","NU"]);
  G('Mercados de capitales',["GS","MS","SCHW","RJF","BK","STT","NTRS","BLK","TROW","BEN","IVZ","AMP","KKR","BX","APO","ARES","MSCI","ICE","CME","NDAQ","CBOE","MKTX","COIN","BYMA","XP"]);
  G('Servicios financieros',["V","MA","AXP","PYPL","FI","FIS","GPN","CPAY","SYF","COF","DFS","SPGI","MCO","EFX","STNE","PAGS"]);
  G('Seguros',["BRK.B","PGR","CB","TRV","ALL","AIG","MET","PRU","AFL","HIG","CINF","L","GL","AIZ","ERIE","WRB","EG","ACGL","AON","MMC","AJG","WTW","BRO"]);
  G('Aeroespacial y defensa',["GE","RTX","BA","LMT","NOC","GD","LHX","TDG","HWM","AXON","HII","TXT","ERJ"]);
  G('Maquinaria',["CAT","DE","CMI","PCAR","ITW","EMR","ETN","PH","DOV","IR","ROK","XYL","FTV","AME","IEX","SNA","PNR","NDSN","SWK","WAB"]);
  G('Transporte terrestre',["UNP","CSX","NSC"]);
  G('Logística',["UPS","FDX","EXPD","CHRW","JBHT","ODFL"]);
  G('Aerolíneas',["DAL","LUV","UAL","AZUL"]);
  G('Transporte',["AUSO","OEST"]);
  G('Conglomerados industriales',["HON","MMM","COME"]);
  G('Servicios comerciales',["WM","RSG","ROL","CTAS","CPRT","VLTO"]);
  G('Servicios profesionales',["ADP","PAYX","VRSK","BR","CSGP"]);
  G('Distribuidoras',["GWW","FAST","URI","MCK","CAH","COR","HSIC"]);
  G('Equipamiento eléctrico',["GEV","HUBB","GNRC"]);
  G('Petróleo y gas',["XOM","CVX","COP","EOG","OXY","HES","FANG","DVN","CTRA","EQT","MRO","APA","EXE","SLB","HAL","BKR","MPC","PSX","VLO","WMB","KMI","OKE","TRGP","TPL","YPFD","CAPX","VIST","PBR","UGP"]);
  G('Eléctricas',["NEE","SO","DUK","AEP","EXC","XEL","ED","WEC","DTE","ETR","PPL","AEE","FE","CMS","CNP","LNT","NI","EVRG","ES","PNW","PCG","AES","CEG","VST","NRG","SRE","D","PEG","PAMP","CEPU","TRAN","EDN","CECO2","CIG","ELP","EBR"]);
  G('Gas',["ATO","TGSU2","TGNO4","METR","CGPA2","DGCU2","GBAN"]);
  G('Agua',["AWK","SBS"]);
  G('Químicas',["LIN","APD","SHW","ECL","PPG","DD","DOW","LYB","CE","ALB","IFF","CF","MOS","FMC","EMN","CTVA","BAK"]);
  G('Metales y minería',["FCX","NEM","NUE","STLD","ALUA","TXAR","VALE","GGB","SID"]);
  G('Materiales de construcción',["VMC","MLM","LOMA","HARG","FERR"]);
  G('Envases',["IP","PKG","BALL","AVY","AMCR","SW","RIGO"]);
  G('Papel y forestales',["WY","CELU","SUZ"]);
  G('Inmobiliarias',["PLD","AMT","EQIX","WELL","SPG","PSA","O","DLR","CCI","CBRE","EXR","VICI","AVB","EQR","IRM","SBAC","INVH","VTR","MAA","ESS","ARE","KIM","DOC","UDR","HST","REG","BXP","FRT","CPT","CRES","IRSA"]);
  G('Software',['ROP']);
  G('Mercados de capitales',['PFG']);
  window.FINTERM_INDUSTRIES=M;
})();
